<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter your stateprovince_checkbox-ui_1</name>
   <tag></tag>
   <elementGuidId>e55bc4ac-5df4-4fef-a6fe-0f5f19150f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkbox-ui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signup_form_YzzU']/div[5]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45a8975e-7dbf-4eb0-8f17-ff7133173048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-ui</value>
      <webElementGuid>f0d721a5-67bf-441e-89b3-a7a03d4ff7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_form_YzzU&quot;)/div[@class=&quot;msaCheckbox checkboxInput section&quot;]/div[1]/div[@class=&quot;field&quot;]/div[@class=&quot;checkbox-ui&quot;]</value>
      <webElementGuid>42ee4c3a-e369-468a-b3a4-9747dff63782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_YzzU']/div[5]/div/div/div</value>
      <webElementGuid>d89b1a16-2d66-4cc0-83b4-95247bc5b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/div/div/div</value>
      <webElementGuid>a7f43fb6-f31c-490b-9e45-228f1430dd9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
