<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter your stateprovince_checkbox-ui</name>
   <tag></tag>
   <elementGuidId>7b30cc61-36e0-4537-a929-4c0b76e0010e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkbox-ui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='signup_form_ktJ4']/div[5]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>722a971b-c3d4-4129-9fd5-4b02277c0fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-ui</value>
      <webElementGuid>f0389611-4b0c-47c5-9c29-145720289f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_form_ktJ4&quot;)/div[@class=&quot;msaCheckbox checkboxInput section&quot;]/div[1]/div[@class=&quot;field&quot;]/div[@class=&quot;checkbox-ui&quot;]</value>
      <webElementGuid>ca9d1ec6-a87a-4a7a-bf75-410c837d2374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_ktJ4']/div[5]/div/div/div</value>
      <webElementGuid>c7aa35a6-cfe0-4ae1-8eb4-ae0e8bf89f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/div/div/div</value>
      <webElementGuid>054895b0-6872-4269-a6d8-ed3ac8b5120f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
