<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your first name_UserLastName</name>
   <tag></tag>
   <elementGuidId>7891ddf3-8de8-4314-b414-3abd90e47883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbb46679-9409-4c1a-85fb-159cee7f2e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserLastName</value>
      <webElementGuid>d3452e5f-9947-462b-94ec-81f15b353324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1dc42373-b6dd-4644-bf59-a5e888831633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserLastName</value>
      <webElementGuid>ab66380f-adc8-4725-ba4a-8ced8c31057e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2130b13-7550-4466-b0aa-2aa86664fe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb15cbbe-993b-4da3-9f94-b1b34a2f4ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserLastName&quot;)</value>
      <webElementGuid>d60a48b5-959f-4a52-a284-b0a2606ac30e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserLastName']</value>
      <webElementGuid>bd4d5378-09ab-4a6b-b20a-b3b62fda8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[6]/div/div[2]/div/div/div[2]/div/div/div/form/div/div/div[2]/div/div/input</value>
      <webElementGuid>2973322d-ebbc-417a-a23b-5b97d07a5c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>af19d246-b9f0-4753-a88a-a81a41916e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserLastName' and @type = 'text' and @name = 'UserLastName']</value>
      <webElementGuid>a103841c-5831-42cb-992a-66e59d51ac14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
