<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your last name_UserEmail_1</name>
   <tag></tag>
   <elementGuidId>4272ba7d-ca9c-4d56-a4e8-5747a5bc803c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserEmail-XlX2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserEmail-XlX2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c97165a-32e4-48be-ac16-d609be770de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserEmail-XlX2</value>
      <webElementGuid>94d10c2a-29ef-4ea7-9c5b-b1767b3a6943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>37b06a8d-522c-4cf5-aac3-a3a18c344c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserEmail</value>
      <webElementGuid>e6ef847b-521b-4c09-ad02-21bd657fd936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a02a621-5140-4235-8ca5-fcd0ab9d721b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e00d8122-61cc-403a-80e5-4a39ddccf132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserEmail-XlX2&quot;)</value>
      <webElementGuid>68495570-1b8d-4474-90e5-c72605744ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserEmail-XlX2']</value>
      <webElementGuid>cbde9868-c2b5-4ac6-ad7a-a8e5d83b8d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_YzzU']/div[2]/div/div/div/div/input</value>
      <webElementGuid>f8196d59-bee1-4bb5-88d4-3e3214d62174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>58ecdd07-cae1-4251-b30e-08bce714eeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserEmail-XlX2' and @type = 'email' and @name = 'UserEmail']</value>
      <webElementGuid>8c4d4d3e-03c4-4cb9-8058-786206b11296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
