<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your last name_UserEmail</name>
   <tag></tag>
   <elementGuidId>1a750841-e400-4030-8ffe-cc45c5a7bf3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e66baf20-8639-4a17-a4e5-10f40ab2f915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserEmail</value>
      <webElementGuid>c55f49d2-8302-47d6-a5d5-63339071c99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>887385d6-4c13-4878-8529-9b207606661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserEmail</value>
      <webElementGuid>d27c2c42-4833-415c-a7fb-a365f5a95ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51b44960-aabd-42ac-acf6-bff8e7ec5065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5eba269-168e-4fdd-bdc3-df69c6c5c1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserEmail&quot;)</value>
      <webElementGuid>e89475b8-571c-4ad4-8747-e54a7ec232ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserEmail']</value>
      <webElementGuid>2fe44371-3ac9-46af-8faf-ef8499aa3adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div[6]/div/div[2]/div/div/div[2]/div/div/div/form/div[2]/div/div/div/div/input</value>
      <webElementGuid>70443587-0e4b-4dca-b049-7d1ea7100e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>1a9b9782-395d-4099-9967-b53eec1bb74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserEmail' and @type = 'email' and @name = 'UserEmail']</value>
      <webElementGuid>41f8dd63-f466-4695-8911-6ea7742afe02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
