<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your first name_UserLastName_1</name>
   <tag></tag>
   <elementGuidId>2d6aee3e-c795-4c92-840e-3dbafdd5521d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserLastName-Fz4U</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserLastName-Fz4U']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f5ac890-25fa-4754-85ee-95fcea06a376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserLastName-Fz4U</value>
      <webElementGuid>39aeb1b8-dfe5-43f2-9d3d-d7d88a680ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36aee380-dc1e-4c86-a081-d3cf66c49d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserLastName</value>
      <webElementGuid>b9e8888f-4e6c-44a9-a7e3-87a3d253689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffa8408d-3cce-487f-892e-4ecbe9841d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7eec5e4a-b47f-401a-a395-d7acffaaf61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserLastName-Fz4U&quot;)</value>
      <webElementGuid>8aaff81d-00f0-4222-9d11-036a565408b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserLastName-Fz4U']</value>
      <webElementGuid>36632451-321b-4d59-8809-603216651d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_YzzU']/div/div/div[2]/div/div/input</value>
      <webElementGuid>ec32d2db-65bf-47e8-b1a0-d0e714d61654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>00e580b8-812d-4aa7-8fb8-aec70c4b1f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserLastName-Fz4U' and @type = 'text' and @name = 'UserLastName']</value>
      <webElementGuid>5d1777ec-4a67-42b2-aa95-d7cc1fa1c64c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
