<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select employee size_UserPhone</name>
   <tag></tag>
   <elementGuidId>e7b52ca3-fcb5-4789-9650-4665091fa49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserPhone-wB37</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserPhone-wB37']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b1517e8-e5a8-4cec-97f0-30d7381b0aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserPhone-wB37</value>
      <webElementGuid>c41e68df-a8a8-4880-a075-6fa4b544d044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>55c03ae0-d478-4558-91f3-1f4d4307cfb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserPhone</value>
      <webElementGuid>0ba1bc57-4abb-45fa-9a4c-2fba81fe80a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf434979-41a1-479b-b596-688673c518ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15eb0a05-2aa0-4a30-8799-3baaeae4f92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserPhone-wB37&quot;)</value>
      <webElementGuid>64951fd4-05ea-45b8-86d9-cb91f48d0cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserPhone-wB37']</value>
      <webElementGuid>ac2620eb-1c05-422d-b47a-190be866f1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_ktJ4']/div[4]/div/div/div/div/input</value>
      <webElementGuid>e0677922-d60c-42b5-8379-299803948fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>85b69c9c-e6a4-4b9a-87d6-0b72dab9a7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserPhone-wB37' and @type = 'tel' and @name = 'UserPhone']</value>
      <webElementGuid>01036e14-f490-4503-b22a-ebbe037b78fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
