<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select employee size_UserPhone_1</name>
   <tag></tag>
   <elementGuidId>32762cb4-b011-42d6-a90c-53e8b9e15b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserPhone-JPMb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserPhone-JPMb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ead06371-23dc-426e-99e1-136888e7a636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserPhone-JPMb</value>
      <webElementGuid>fa51a59e-9971-426d-bb8a-6a8af7512707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>05dd7daa-059e-4ede-8911-c8f012b0bcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserPhone</value>
      <webElementGuid>3f3195b2-32a7-48d9-a3fc-d6e5d78dd2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98f92231-f54b-4a9f-9ebe-7a22b3e62125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f27a5cbe-e0ab-4f4c-960e-2c7f7df681c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserPhone-JPMb&quot;)</value>
      <webElementGuid>17b41110-d5a9-4f1a-904d-7bababe46379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserPhone-JPMb']</value>
      <webElementGuid>55f6cabb-4da2-4035-8f67-9b229e97743c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_YzzU']/div[4]/div/div/div/div/input</value>
      <webElementGuid>171574c6-0996-4ab9-a8e6-2119f12e8738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>0800bdf2-5555-42aa-aa32-412e42e57011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserPhone-JPMb' and @type = 'tel' and @name = 'UserPhone']</value>
      <webElementGuid>c642c8cc-b96e-4f88-9322-484d51a96527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
