<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up now to start your free sales _9c5179</name>
   <tag></tag>
   <elementGuidId>4b879ab9-f5f8-42e9-8f37-c96ede9ce864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserFirstName-Zs5y</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserFirstName-Zs5y']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d66d7c76-9fbd-4efe-97a3-727e12ae8bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserFirstName-Zs5y</value>
      <webElementGuid>c811a339-4fa1-43b5-acc3-004851211985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b101e213-5671-4538-9e6c-b7312b0de82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserFirstName</value>
      <webElementGuid>c00b2ae9-1862-4e02-be71-6a2a2f4fd2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63d60f55-2374-4f13-a9d4-7daf920421ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7363b8c1-8338-4acb-8363-1312fe7362ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserFirstName-Zs5y&quot;)</value>
      <webElementGuid>f3d5b191-b87b-4044-9288-069de42f331d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserFirstName-Zs5y']</value>
      <webElementGuid>8487baf5-c837-4237-8ff8-f43429f9f3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signup_form_YzzU']/div/div/div/div/div/input</value>
      <webElementGuid>2ce93b91-aa0e-4a98-adcb-4d12517aefc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>3716ea87-470f-46d5-8253-a1f6dc1269cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserFirstName-Zs5y' and @type = 'text' and @name = 'UserFirstName']</value>
      <webElementGuid>0e3a746c-508c-452b-a7fc-9824f4faa043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
