<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Angelica Ramos_row-25-position</name>
   <tag></tag>
   <elementGuidId>29920b7c-fabf-427a-8fca-e31faa33d306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row-25-position</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='row-25-position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edbacca6-ee9e-40b4-8154-92b00552f753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a61123b3-0335-4942-bf61-0b9682d12871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row-25-position</value>
      <webElementGuid>37078d54-64bd-4469-9a39-f99037c34154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>row-25-position</value>
      <webElementGuid>21341015-1909-4e7b-930f-809da0321d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Chief Executive Officer (CEO)</value>
      <webElementGuid>c2d1a8ad-49e6-452b-947d-af495f2fe5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-25-position&quot;)</value>
      <webElementGuid>6cf40040-d6ce-4484-b575-94d58dcc4393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='row-25-position']</value>
      <webElementGuid>a16b5b59-744f-4c61-8e0c-927e4f71eec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>e68d118c-5e99-4e6d-8787-809177c5f77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>ac86c809-44ef-4e8a-bf3c-d0a73ca642fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'row-25-position' and @name = 'row-25-position']</value>
      <webElementGuid>c34080ab-2013-4900-94fd-86612337692c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
