<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Angelica Ramos_row-25-age</name>
   <tag></tag>
   <elementGuidId>cd56c7b6-c57e-4d38-bd00-5f575f7e637d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#row-25-age</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='row-25-age']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82d3880f-2565-4522-8adf-9d152c9cde25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4125c05-d68d-40cc-96a2-3e5beeba0921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>row-25-age</value>
      <webElementGuid>e5c8ac78-8d03-4bd2-b7ff-851f0943e7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>row-25-age</value>
      <webElementGuid>e60609bd-76d3-4042-b9f4-84e7f6f0c38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>3c3ba385-1ac2-46f5-a927-3c4828633a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row-25-age&quot;)</value>
      <webElementGuid>5aa895bd-b511-4bf4-9703-1b8984273ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='row-25-age']</value>
      <webElementGuid>5a23c313-1af9-4220-ae8e-cd65801383e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>39b5f9c5-fce7-4997-b57f-db9d4ff3ac3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>38b2431b-f4d3-4817-8716-dbed873679f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'row-25-age' and @name = 'row-25-age']</value>
      <webElementGuid>60b6f2cf-5eb3-4447-8f01-dddce111c926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
