<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Angelica Ramos</name>
   <tag></tag>
   <elementGuidId>3355bb06-0c43-4e75-9036-6b68ad5cf747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.sorting_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr[2]/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6f399b9d-2e43-40a7-a119-8efeca395821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>c0d06743-9f7f-4d79-8734-0f9ca990923b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Angelica Ramos</value>
      <webElementGuid>d6601dd5-0d2a-4915-8f83-11f1129dc8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>beaf9b53-516c-45a4-8f19-c7c496a14b3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr[2]/td</value>
      <webElementGuid>8ae6f8b9-5ede-4b24-8810-cd3c5090f0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airi Satou'])[1]/following::td[4]</value>
      <webElementGuid>bf1f1c6a-8020-45ad-9dc0-24b2362d9ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office'])[1]/following::td[5]</value>
      <webElementGuid>faca2529-6494-455e-8381-1509fe2fc6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ashton Cox'])[1]/preceding::td[4]</value>
      <webElementGuid>6f853f14-be31-45ce-b181-f61561648aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bradley Greer'])[1]/preceding::td[8]</value>
      <webElementGuid>8b6bde8c-39fe-4459-b233-d81f48089047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Angelica Ramos']/parent::*</value>
      <webElementGuid>d76fa92d-4df7-4feb-b67c-a61f6de03dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>31cdf232-8daa-4bc1-a95b-47b838dab5f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Angelica Ramos' or . = 'Angelica Ramos')]</value>
      <webElementGuid>c5ca6fae-653e-4db9-ad5f-cf1647ff069d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
